assert(nansum(sum(WhatIsDoneAlready(2,{'DummySpecificSample', 'DummyRandGenSample',...
    'DummyAllNewDetects','DummyOnlyWhenEyeDetected'},5,2)))==162619.8, ...
    'Dummy Folder Value Total is 162619.8 if you add all the columns together and ignore the NaNs')